/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4d241a316af231866e2a48822516c980)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/cloudflare");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
