// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwiqwuohbcvhuvtlxlvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3aXF3dW9oYmN2aHV2dGx4bHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDcwOTEsImV4cCI6MjA2NjI4MzA5MX0.8j4C62pwhQ7QKUYFoWu4ZiCiZ7dRGiY9ArpHr5TX1wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);